stages:
  - build
  - deploy

build_liv_front_on_recette:
  stage: build
  image: node:12.18.0
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq openssh-client 
    # add SSH_PRIVATE_KEY in agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    # On minifie les src node ds le livrable dist
    - (which yarn || npm i -g yarn@1.15.2)
    - cd ./front
    - yarn install 
    - yarn run build && cp -RT build dist
    # On livre le livrable dist sur le 
    - ssh -o StrictHostKeyChecking=no gitlab@$IP_RECETTE "mkdir -p $WORKDIR_SERVER/nginx/front"
    - scp -o StrictHostKeyChecking=no -r ./dist gitlab@$IP_RECETTE:$WORKDIR_SERVER/nginx/front
  only:
    refs:
      - feature/init-admin
    # changes:
    #   - ./front/**/*

build_liv_front-admin_on_recette:
  stage: build
  image: node:12.18.0
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq openssh-client 
    # add SSH_PRIVATE_KEY in agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    # On minifie les src node ds le livrable dist
    - (which yarn || npm i -g yarn@1.15.2)
    - cd ./front-admin
    - yarn install 
    - yarn run build && cp -RT build dist
    # On livre le livrable dist sur le 
    - ssh -o StrictHostKeyChecking=no gitlab@$IP_RECETTE "mkdir -p $WORKDIR_SERVER/nginx/front-admin"
    - scp -o StrictHostKeyChecking=no -r ./dist gitlab@$IP_RECETTE:$WORKDIR_SERVER/nginx/front-admin
  only:
    refs:
      - feature/init-admin
    # changes:
    #   - ./front-admin/**/*

build_api_image:
  stage: build 
  image:
      name: gcr.io/kaniko-project/executor:debug
      entrypoint: [""]
  script:
    # On construit l'image docker du composant front et on la sauvegarde dans le registry gitlab
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dockerfile_api --destination $CI_REGISTRY_IMAGE:api
  only:
    refs:
      - feature/init-admin
    # changes:
    #   - ./api/**/*

deploy_application_on_recette:
  stage: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq openssh-client 
    # add SSH_PRIVATE_KEY in agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no docker-compose.yml docker-compose.recette.yml gitlab@$IP_RECETTE:$WORKDIR_SERVER
    - ssh -o StrictHostKeyChecking=no gitlab@$IP_RECETTE "mkdir -p $WORKDIR_SERVER/nginx"
    - scp -o StrictHostKeyChecking=no nginx/recette.conf gitlab@$IP_RECETTE:$WORKDIR_SERVER/nginx/
    - ssh -o StrictHostKeyChecking=no gitlab@$IP_RECETTE "
                cd $WORKDIR_SERVER &&
                echo -e 'DATABASE_URL=$DATABASE_URL\nMYSQL_DATABASE=$MYSQL_DATABASE\nMYSQL_USER=$MYSQL_USER\nMYSQL_PASSWORD=$MYSQL_PASSWORD\nEMPLOI_STORE_URL=$EMPLOI_STORE_URL\nENTERPRISE_URL=$ENTERPRISE_URL\nEMPLOI_STORE_ID=$EMPLOI_STORE_ID\nEMPLOI_STORE_SECRET=$EMPLOI_STORE_SECRET' > .env &&
                docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&
                docker-compose -f docker-compose.yml -f docker-compose.recette.yml pull && 
                docker-compose -f docker-compose.yml -f docker-compose.recette.yml up -d"
  only:
    refs:
      - feature/init-admin
  when: on_success # s'exécutera uniquement si le job `build` passe
