stages:
    - build-application
    - deploy-application-on-recette

build_application :
    stage: build-application
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
      - echo $NODE_ENV
      # On construit l'image docker du composant front et on la sauvegarde dans le registry gitlab
      - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor --dockerfile $CI_PROJECT_DIR/dockerfile_front --destination $CI_REGISTRY_IMAGE:front
    only:
      - b

deploy_application_on_recette:
  stage: deploy-application-on-recette
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq openssh-client 
    # add SSH_PRIVATE_KEY in agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
  script:
    #- ssh -o StrictHostKeyChecking=no gitlab@192.168.4.135:. 
    - scp -o StrictHostKeyChecking=no docker-compose.yml docker-compose.recette.yml gitlab@192.168.4.135:$WORKDIR_SERVER
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.4.135 "cd $WORKDIR_SERVER && ./deploy.sh $CI_REGISTRY $CI_REGISTRY_USER $CI_REGISTRY_PASSWORD"

    
        
    
