version: '2.4'
services:
  nginx:
    image: nginx:1.17.10
    restart: unless-stopped
    ports:
      - '80:80'
    cpus: '0.50'
    mem_limit: 300M
    volumes:
      - './front:/home/front'
      #- './front-admin:/home/front-admin'
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'
      - './logs/nginx:/var/log/nginx'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.10

  node:
    restart: unless-stopped
    cpus: '2.5'
    mem_limit: 4G
    build:
      context: .
      dockerfile: dockerfile_api
    volumes:
      - './api:/home/api'
    expose:
      - '8080'
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.100
    depends_on:
      - 'db'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMPLOI_STORE_URL=${EMPLOI_STORE_URL}
      - ENTERPRISE_URL=${ENTERPRISE_URL}
      - EMPLOI_STORE_ID=${EMPLOI_STORE_ID}
      - EMPLOI_STORE_SECRET=${EMPLOI_STORE_SECRET}
      - API_CITIES=${API_CITIES}
  
  front:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    cpus: '0.50'
    mem_limit: 2G
    volumes:
      - './front:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.110
    stdin_open: true

  front-admin:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    cpus: '0.50'
    mem_limit: 2G
    volumes:
      - './front-admin:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.111
    stdin_open: true

  db:
    image: postgres:10.4
    restart: always
    cpus: '4.0'
    mem_limit: 8G
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.150
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Paris
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=200'
      - '-c'
      - 'shared_buffers=2GB'
      - '-c'
      - 'effective_cache_size=6GB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'checkpoint_completion_target=0.7'
      - '-c'
      - 'wal_buffers=16MB'
      - '-c'
      - 'default_statistics_target=100'
      - '-c'
      - 'random_page_cost=4'
      - '-c'
      - 'effective_io_concurrency=2'
      - '-c'
      - 'work_mem=5242kB'
      - '-c'
      - 'min_wal_size=1GB'
      - '-c'
      - 'max_wal_size=4GB'
      - '-c'
      - 'max_worker_processes=4'
      - '-c'
      - 'max_parallel_workers_per_gather=2'
      - '-c'
      - 'max_parallel_workers=4'
       
       
networks:
  mobiville_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1

volumes:
  postgres-data:
