version: '3.3'
services:
  nginx:
    image: nginx:1.17.10
    restart: unless-stopped
    ports:
      - '80:80'
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.5'
    volumes:
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'
      - './logs/nginx:/var/log/nginx'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.10

  api:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.5'
    build:
      context: .
      dockerfile: dockerfile_api
    volumes:
      - './api:/home/api'
    expose:
      - '8080'
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.20
    depends_on:
      - 'db'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMPLOI_STORE_URL=${EMPLOI_STORE_URL}
      - ENTERPRISE_URL=${ENTERPRISE_URL}
      - EMPLOI_STORE_ID=${EMPLOI_STORE_ID}
      - EMPLOI_STORE_SECRET=${EMPLOI_STORE_SECRET}
    stdin_open: true
  
  front:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    deploy: 
      resources:
        limits:
          memory: 2G
          cpus: '0.50'
    volumes:
      - './front:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.30
    stdin_open: true

  front-admin:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '0.50'
    volumes:
      - './front-admin:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.40
    stdin_open: true

  db:
    image: mariadb:10
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.50
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Paris
       
       
networks:
  mobiville_network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.0.0.0/16
