version: '2.4'
services:
  node:
    environment:
      - NODE_ENV=production
      - ZEN_ENV=production

  front:
    environment:
      - NODE_ENV=production
      - REACT_APP_ZEN_ENV=production

  front-admin:
    environment:
      - NODE_ENV=production
      - REACT_APP_ZEN_ENV=production
