version: "3.9"
services:
  nginx:
    image: nginx:1.17.10
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - './nginx/recette.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/front/dist:/home/front'
    depends_on:
      - "api"
      - "db"

  api:
    build:
      context: .
      dockerfile: dockerfile_api
    expose:
      - '8080'
    depends_on:
      - 'db'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMPLOI_STORE_URL=${EMPLOI_STORE_URL}
      - ENTERPRISE_URL=${ENTERPRISE_URL}
      - EMPLOI_STORE_ID=${EMPLOI_STORE_ID}
      - EMPLOI_STORE_SECRET=${EMPLOI_STORE_SECRET}

  db:
    image: mariadb:10
    expose:
      - "3306"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Paris    
    volumes:
      - ./tests/db:/docker-entrypoint-initdb.d

  e2e:
    image: cypress/included:3.2.0
    depends_on:
      - "nginx"
      - "db"
      - "api"
    entrypoint: /scripts/wait-for-it.sh api:8080 -- cypress run
    volumes:
      - ./tests:/e2e
      - ./scripts:/scripts
    working_dir: /e2e
    environment:
      - CYPRESS_baseUrl=http://nginx
      - NODE_ENV=test
      - REACT_APP_ZEN_ENV=test
      - TZ=Europe/Paris
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api"]
      interval: 30s
      timeout: 10s
      retries: 5