version: '2.4'
services:
  nginx:
    image: nginx:1.17.10
    restart: unless-stopped
    ports:
      - '80:80'
    cpus: '0.50'
    mem_limit: 300M
    volumes:
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'
      - './logs/nginx:/var/log/nginx'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.10

  api:
    restart: unless-stopped
    cpus: '2.5'
    mem_limit: 4G
    build:
      context: .
      dockerfile: dockerfile_api
    volumes:
      - './api:/home/api'
    expose:
      - '8080'
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.100
    depends_on:
      - 'db'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - EMPLOI_STORE_URL=${EMPLOI_STORE_URL}
      - ENTERPRISE_URL=${ENTERPRISE_URL}
      - EMPLOI_STORE_ID=${EMPLOI_STORE_ID}
      - EMPLOI_STORE_SECRET=${EMPLOI_STORE_SECRET}
      - API_LOI_LITTORAL=${API_LOI_LITTORAL}
    stdin_open: true
  
  front:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    cpus: '0.50'
    mem_limit: 2G
    volumes:
      - './front:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.110
    stdin_open: true

  front-admin:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile_front
    cpus: '0.50'
    mem_limit: 2G
    volumes:
      - './front-admin:/home/front'
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.111
    stdin_open: true

  db:
    image: mariadb:10
    restart: always
    cpus: '4.0'
    mem_limit: 8G
    networks:
      mobiville_network:
        ipv4_address: 172.0.0.150
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Europe/Paris
       
       
networks:
  mobiville_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1
