version: "3.3"
services:
  nginx:
    volumes:
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'

  api:
    build:
      context: .
      dockerfile: dockerfile_api
    environment: 
      - NODE_ENV=recette
    volumes:
      - './api:/home/api'
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.5'

  front:   
    build:
      context: .
      dockerfile: dockerfile_front
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    volumes:
      - './front:/home/front'
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.30
    stdin_open: true
    environment:
      - NODE_ENV=development

  front-admin:
    build:
      context: .
      dockerfile: dockerfile_front
    restart: unless-stopped
    expose:
      - '3000'
    environment:
      - TZ=Europe/Paris
    volumes:
      - './front-admin:/home/front'
    networks:
      mobiville_network:
        ipv4_address: 173.0.0.40
    stdin_open: true
    environment:
      - NODE_ENV=development
