version: "2.4"
services:
  api:
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "3306:3306"

  front:
    environment:
      - NODE_ENV=development

  front-admin:
    environment:
      - NODE_ENV=development
