version: "3.3"
services:
  nginx:
    volumes:
      - './nginx/recette.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/front/dist:/home/front'
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.5'

  api:
    image: registry.beta.pole-emploi.fr/mobiville/mobiville:api
    environment: 
      - NODE_ENV=recette
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.5'

  db:
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
  
  # front-admin:
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #         cpus: '0.50'
