version: "3.3"
services:
  api:
    environment:
      - NODE_ENV=development

  db:
    ports:
      - "3306:3306"

  front:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: dockerfile_front


  front-admin:
    environment:
      - NODE_ENV=development
